List<String>Resimlerim=[
  'https://4.bp.blogspot.com/-q8ImPQNGXII/XOpi95FgV9I/AAAAAAAEFgg/FuTpdghP6mwN_XgSUNlrpP5zZb4omWfTQCK4BGAYYCw/s1600/kadir6.jpg',
  'https://i.pinimg.com/originals/41/63/52/416352f4786884ee811c7b4b3ae93e5f.gif',
  'https://www.kamudanhaber.net/images/upload/resized_785e6-9bcfba541.jpg',
  'https://cokiyiabi.com/wp-content/uploads/2016/07/kadir-gecesi-gif-mesaj.gif',
  'https://i2.milimaj.com/i/milliyet/75/0x410/5f98683f55427f1df00f5fa0.jpg',
  'https://cokiyiabi.com/wp-content/uploads/2016/07/hareketli-kadir-gecesi-gifleri.gif',
  'https://assets.dogannet.tv/img/75/740x0/5ec375f266a97c3d21978288',
  'https://2.bp.blogspot.com/-rVLMtYT6rrE/UfUCWjsi_DI/AAAAAAAAURs/7n0JIMf31Qo/s1600/kandil+tebri%C4%9Fi.gif',
  'https://yenikapihaber.com/d/gallery/68065_2.jpg',
  'http://www.balturk.org.tr/wp-content/uploads/2020/02/mektup303.gif',
  'http://www.balikesirim.net/images/upload/kadir_gecei1.jpg',
  'https://ayindasontango.files.wordpress.com/2017/03/4304506_88c4b.gif',
  'https://i.superhaber.tv/storage/files/images/2020/05/18/errfdsrd-MTpZ_cover.jpg',
  'https://cokiyiabi.com/wp-content/uploads/2016/07/kadir-gecesi-gif-mesaj.gif',
  'https://i.pinimg.com/originals/dd/2d/8c/dd2d8c8c2e6ad2e1987449805e74132b.jpg',
  'https://islamcokguzel.files.wordpress.com/2012/08/kadirgecesiislamcokguzel.gif?w=584',
  'https://cdn.iha.com.tr/Contents/images/2020/21/3305055.jpg',
  'https://1.bp.blogspot.com/-tUqTwSkSeCo/WUl4rA2pYWI/AAAAAAACih0/7YcuwYoiA8QV8vhNh83mkHmprEJyLebHACK4BGAYYCw/s1600/mektup362.gif',
  'https://1.bp.blogspot.com/-2ZIG7ZAymuI/WUl1jFp-8YI/AAAAAAACihg/0NaPHg9k-oAXU6bL4uVlChEDxLCeSaIVwCLcBGAs/s1600/mektup360.gif',
  'https://i.pinimg.com/originals/38/b4/08/38b408098a854628d0b6c5bcc6793139.gif',
  'https://i.ytimg.com/vi/kupmBpSPCFI/hqdefault.jpg',
  'http://www.kamubulteni.com/images/upload/13_3.gif',
  'https://iatkv.tmgrup.com.tr/647ea8/0/0/0/0/0/0?u=https%3A%2F%2Fitkv.tmgrup.com.tr%2F2021%2F05%2F07%2Fkadir-gecesi-mesajlari-sozleri-2021-en-guzel-anlamli-hadisli-resimli-kadir-gecesi-mesajlari-kisa-uzun-sozleri-1620413978100.jpg&mw=600',
  'https://i.pinimg.com/originals/b4/50/71/b45071999972bec1bb13349c5c0a2154.gif',
  'https://assets.dogannet.tv/img/75/740x0/5ec36fcfae298b0e02aeea20',
  'https://img1.picmix.com/output/pic/normal/3/5/7/4/7764753_f4a5b.gif',
  'http://sendeyim.com/uploads/resimli_sozler/resimli-kadir-gecesi-mesajlari_99604639.jpg',
  'https://img1.picmix.com/output/pic/normal/0/1/8/5/6665810_5ec48.gif',
  'https://149572216.v2.pressablecdn.com/wp-content/uploads/2019/05/en-guzel-ve-anlamli-kadir-gecesi-mesajlari-kadir-gecesi-ve-cuma-gunu-icin-whatsapp-resimli-kutlama-mesajlari-14.jpg',
  'http://1.bp.blogspot.com/-dcdcFttl2Kw/VlUwqm3FveI/AAAAAAAAAaA/aKA5paWa-n4/s1600/03.gif',
  'https://www.haberankara.com/images/upload/609617c3b57f152190ba1b2f.jpg',
  'https://psparena.com/wp-content/uploads/2018/07/kadir-geceniz-mubarek-olsun.gif',
  'https://cdn.karar.com/other/2021/05/08/kadir-gecesi1-1559256390.jpg',
  'https://i.pinimg.com/originals/4d/10/44/4d10446adeae98cb5c73e9c44cfb5539.gif',
  'https://i.pinimg.com/originals/86/d3/42/86d3420516b846d222575564c4848810.jpg',
  'https://cokiyiabi.com/wp-content/uploads/2016/07/animasyonlu-kadir-gecesi-gif.gif',
  'https://www.huzursayfasi.com/images/editor/images/kadir-gecesi-mesajlar%C4%B1%2811%29.jpg',
  'https://i.ytimg.com/vi/B46Gb77XMBk/hqdefault.jpg',
  'https://i.ytimg.com/vi/gmas31TB6NA/hqdefault.jpg',
  'https://www.risalehaber.com/d/other/kadir-gecesi-mesajlari.jpg.gif',
  'https://i2.milimaj.com/i/milliyet/75/750x0/6094609e86b247020499e476.jpg',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTqo3JNjz2DF1cF_gpIm1qF4L1fgea4h-tMPN8zuEc6B9JxSr6NN1-iLlMOuAU2JoJW-L8&usqp=CAU',
  'https://isbh.tmgrup.com.tr/sb/album/2021/05/08/bin-aydan-daha-hayirli-kadir-gecesi-mesajlari-ve-sozleri-2021-anlamli-ve-resimli-kadir-gecesi-mesajlari-kisa-uzun-ve-duali-hayirli-kandiller-mesaji-so-1620465050887.jpg',
  'https://i.pinimg.com/originals/b9/34/e5/b934e5f2b5d39d642a4e0439d200ffed.gif',
  'https://im.haberturk.com/2020/05/19/2684971_bfcb675fa42ffc3c947988a1cd568f78_640x640.jpg',
  'https://2.bp.blogspot.com/-VDjlTTMmwbI/Wh5pvrlxAkI/AAAAAAADVyM/Gg-fw3iKrXAziJr6ZDnCWoSJdmT0RALTQCLcBGAs/s1600/MEKTUP6801.gif',
  'https://i4.hurimg.com/i/hurriyet/75/0x0/5ec3de6d2269a21980a6f8a0.jpg',
  'https://i.pinimg.com/originals/7a/18/86/7a1886baa1fa0fb7f45beccb831f4f87.gif',
  'https://i.pinimg.com/originals/04/7f/9a/047f9a782a34fc93e5adb12f5c696f78.jpg',
  'https://cokiyiabi.com/wp-content/uploads/2017/04/hareketli-mirac-kandili-mesajlari-indir.gif',
  'https://www.incezeka.com/wp-content/uploads/2022/04/kadir-gecesi-mesajlari-sozleri-2022-resimli-duali-yeni-degisik-ozel-sevgiliye-anlamli-ayetli-whatsapp-kandil-mesajlari-2022-10.jpg',
  'https://cokiyiabi.com/wp-content/uploads/2016/04/Hareketli-Kandil-Mesajlari-1.gif',
  'https://photo.haberler.com/galeri/2019/05/30/resimli-kadir-gecesi-mesajlari-2019-en-guzel-714763_5280_2_b.jpg',
  'https://i.pinimg.com/originals/6c/39/dd/6c39ddeea6a378f45083d10e3936ae40.gif',
  'https://www.nesnem.com/sozleri/resimli/resim/resmi-indir-FB_IMG_1559310903195.jpg84c468a6.jpg',
  'https://cokiyiabi.com/wp-content/uploads/2017/04/mirac-kandili-hareketli-gifler.gif',
  'https://www.uyan32.com/wp-content/uploads/2020/05/Resimli-Kadir-Gecesi-Mesajlari.jpg',
  'https://cokiyiabi.com/wp-content/uploads/2017/04/mirac-kandili-gif-1.gif',
  'https://www.dinimizde.com/wp-content/uploads/2020/05/2020-Kad%C4%B1r-Geces%C4%B1-Res%C4%B1ml%C4%B1-mesajlar%C4%B1-ve-sozler%C4%B1-.jpg',
  'https://i.pinimg.com/originals/5b/76/a8/5b76a83ef50019a9891ef929bee9b5a6.gif',
  'https://www.ekovitrin.com/images/haberler/2020/05/19_mayis_2020_en_guzel_kadir_gecesi_mesajlari_h81200_f935f.jpg',
  'https://cokiyiabi.com/wp-content/uploads/2017/03/kandil-mesajlari-hareketli.gif',
  'https://ia.tmgrup.com.tr/14151d/0/0/0/0/0/0?u=https://i.tmgrup.com.tr/fikriyat/album/2019/05/28/1559026138346.jpg&mw=752',
  'https://yunti.files.wordpress.com/2019/04/kandil_01.gif',
  'https://i.pinimg.com/originals/6a/aa/b2/6aaab2b84f5339b5892d524533f4bc9b.jpg',
  'https://i.pinimg.com/originals/6b/a8/cf/6ba8cf471a55a4a2465ce602e4879b37.gif',
  'https://i0.wp.com/www.incezeka.com/wp-content/uploads/2021/05/Duali-kadir-gecesi-resimli-mesajlari-1.jpg?fit=700%2C364&ssl=1',
  'https://i.pinimg.com/originals/83/bb/72/83bb72939d89218fc34e270cbfa41756.gif',
  'https://www.twitsozler.com/upload/photos/2020/02/bsZziz2EXjcBuashhDwh_23_de589dbaacd73b23a5f9368b4b90952a_image.jpg',
  'https://i.pinimg.com/originals/1a/af/3a/1aaf3a3e9fefb39f4941fb4d2c3d64a1.gif',
  'https://i.cnnturk.com/i/cnnturk/75/700x0/609617c5b57f152190ba1b39.png',
  'https://4.bp.blogspot.com/-7xN-t-sKcHI/WiB0_aEcgLI/AAAAAAADWRs/_JKIMDEkHxQO9T7R8LVPIZ1IC7xtnHF5QCK4BGAYYCw/s1600/mektup7024.gif',
  'https://www.twitsozler.com/upload/photos/2020/02/p7yOhokID1sL9lgzlRAa_22_de55f84f9ddd8cf97f0cc1c650dd8fc7_image.jpg',
  'https://2.bp.blogspot.com/-rVLMtYT6rrE/UfUCWjsi_DI/AAAAAAAAURs/7n0JIMf31Qo/s1600/kandil+tebri%C4%9Fi.gif',
  'https://i.pinimg.com/originals/ea/20/b9/ea20b9783ab259b9f110170fb32086da.jpg',
  'http://abload.de/img/forumelele-kadir-geceugak1.gif',
  'https://www.gastepress.com/images/haberler/2021/05/baskanlardan-kadir-gecesi-mesaji.jpg',
  'https://i0.wp.com/www.kandilmesaji.com/wp-content/uploads/2016/06/kandil-mesaji-01.gif?fit=615%2C300',
  'https://www.incesoz.com/wp-content/uploads/2019/01/kadirgecesi.jpg',
  'https://2.bp.blogspot.com/-3N8IwWjI350/Wh5jHxt0F9I/AAAAAAADVx0/UoWf-ISjK30ORUoE8Ow_gmegCHI15vqzACLcBGAs/s1600/mektup6800.gif',
  'https://assets.dogannet.tv/img/75/740x0/5ec37665ae298b0e02aeea48',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQEfxdwmuRcWMMeJbN6yIhSr3-MG9tVmgnQOA&usqp=CAU',
  'https://assets.dogannet.tv/img/75/740x0/5ec3761666a97c3d229985f6',
  'https://abload.de/img/dinigifgifsdsnebru2f54bi5p.gif',
  'https://img.memurlar.net/galeri/12728/39d8a347-8356-e711-80d3-a0369f7d149c.jpg?width=800',
  'https://www.muhammedinur.com/photos/galleries/mesajresimleri/efe44.gif',
  'https://i.pinimg.com/736x/9f/40/a1/9f40a10ab74f0a031d40e20b650a8ae2.jpg',
  'https://i.pinimg.com/originals/f8/46/d8/f846d869028b3a0392192a1fe1c7858c.gif',
];

List<String>YaziliMesajlar=[
'Ya Rab, kusurumuzu affet. Bizi Kendine kul kabul et. Emanetini kabzetmek zamanına kadar bizi emanette emin kıl. Amin! Kadir geceniz mübarek olsun.',
' Allah"ım rızkımıza bolluk, kalbimize ferahlık, ömrümüze bereket ver Amin. Kadir geceniz mübarek olsun.',
'Mübarek Kadir Gecenizi kutlar, her şeyin gönlünüzden geçtiği gibi olmasını temenni ederim. Kandiliniz mübarek olsun.',
'Gül sevginin tacıdır, her bahar bir gül taçlanır. O gül ki Muhammeti hatırlatır. Onu hatırlayana gül koklatır. Gül kokulu sevgi dolu nice kandillere..',
' Bin aydan daha hayırlı olan Kadir Gecesinde, kainatın yaratıcısı ve alemlerin Rabbi bağışlayıcı ve acıyıcı yüce Allah tüm dualarınızı kabul etsin',
'Dertlerimiz kum tanesi kadar küçük, sevinçlerimiz Nisan yağmuru kadar bol olsun. Bu mübarek geceniz sevapla dolsun. Kadir Geceniz Mübarek Olsun.',
'Bugün ettiğiniz bütün dualar göklere yükselip, tek tek kabul olup üzerinize sağanak gibi yağsın inşallah. Kadir Geceniz mübarek olsun.',
' Hayırlı Kandiller... Yüce Rabbim bu güzel gecede bizlere onun rızasını kazanacak ameli versin, Kadir geceniz hayırlı olsun',
'Yüreğine bin damla serpilsin ki yüreğin ferahlasın, günlerine bin tatlı mutluluk dolsun ki huzur dolu bir yaşamın olsun, bu mübarek Kadir gecesinde tüm dualarınız kabul olunsun.',
'Varlığı ebedi olan, merhamet sahibi, adaletli Yüce Allah kendisine dua edenleri geri çevirmez. Dualarınızın Rabbin yüce katına iletilmesine vesile olan kandiliniz mübarek olsun.',
'Bu güzel gecelerin feyzi üzerinize, rahmeti geçmişinize, bereketi evinize, nuru ahiretinize, sıcaklığı yuvanıza dolsun. Kadir Geceniz mübarek olsun',
'Bugün ellerini semaya gönlünü Mevla’ya aç. Bugün günahlardan olabildiğince kaç. Bugün en gizli incilerini onun için saç. Kadir Geceniz mübarek olsun.',
  "Allah'ım.Geçmiş ve gelecek, gizli ve açık bütün günahlarımı bağışla.Benim ilâhım Sensin.Senden başka ilâh yoktur. '(Buhârî, Tevhîd, 35)' Kadir geceniz mübarek olsun.",
  "Dua et,Belki de bütün umutların avuç içlerinde ki o dua da saklıdır… Kadir geceniz mübarek olsun",
  "Gün vardır bin aydan hayırlıdır. Rabbim tüm dualarımızı kabul eylesin. Tüm Müslüman aleminin kadir gecesi mübarek olsun",
  "Dünya telaşını bırak bir kenara. Rabbine yönel ondan iste. Kadir gecemiz mübarek olsun.",
  "Ya Rabbi.Hayatımızı Kur'an ve Sünnet çizgisinde Hak dostluğu, takva, azimet ve ihsan şuuru çerçevesinde yaşat. '(Amin)' Kadir Gecemiz Mübarek Olsun.",
  "Kadir gecesinin sabahında, hepimizin günahlardan temizlenmiş, Allah'ın rahmetine mazhar olmuş kullardan olmamız duasıyla...",
  "Ömrümüzün bir muhasebesini yapabilmek ve hayatımızı 'helal ve haram' sınırlarını gözeterek bir istikamet çizebilme ümidiyle, Kadir Gecemiz Mübarek Olsun.",
  "Bin aydan daha hayırlı olan mübarek Kadir Gecesi'nin tüm İslam alemine hayırlı olmasını temenni ederim. Kandilimiz mübarek olsun...",
  "Hem Ramazan ayının bereketi hem de Kadir Gecesi'nin hayrı üzerimize olsun. Hayırlı kandiller...",
  "Allahım bizleri rehmetinin o engin lütfuyla  bağışla, bize merhamet et. Bize hidayet ver ve sıratı müstakimden ayırma. Hayırlı kandiller. Kadir Geceniz mübarek olsun.",
  "Nuruyla alemimizi şereflendiren Peygamber Efendimizin -s.a.v, şefaatine nail olmanız dileğiyle Kadir Geceniz mübarek olsun.",
  "Mübarek Kadir gecesinin İslam aleminin yeniden dirilişine vesile olarak dualarınızın kabul olması dileğiyle, Rabbim yar ve yardımcınız olsun. Kandilimiz mübarek olsun.",
  "Gül-i Muhammed-i olanlara selam olsun, selam diyarından geçenlere bahar olsun, gönlü hazan olanların gönlü gülistan olsun, mübarek kandiliniz kutlu olsun.",
  "Allahım bizleri rahmetinin o engin lütfuyla  bağışla, bize merhamet et. Bize hidayet ver ve sıratı müstakimden ayırma. Hayırlı kandiller. Kadir Geceniz mübarek olsun.",
  "Ey Rabbim şu sonsuz merhamet ve rahmetinden bir damla da olsa, nasiplenmeyi hakeden kullarında eyle bizi. Amin.Kadir Geceniz hayırlı olsun.",
  "Allah'ım rızkımıza bolluk, kalbimize ferahlık, ömrümüze bereket ver Amin. Kadir geceniz mübarek olsun.",
  "Gün vardır, bin yıldan uzun gelir bize, bir yıl vardır bir günden kısa gelir bize. Bire bin yazılan bu gecede dua edelim Rabbimize. Kadir geceniz mübarek olsun.",
  "Bin aydan daha hayırlı olan Kadir Gecesi'nde, kainatın yaratıcısı ve alemlerin Rabbi dualarınızı kabul etsin.",
  " Ramazan’ı Şerif’in 27. gecesi, bin aydan daha hayırlı, sema kapılarının açıldığı, dua ve tövbelerin kabul edildiği “Kadir Gecemiz” mübarek olsun.",
  "Allah’ım sen affedersin ve affetmeyi seversin. Benim günahlarımı da bağışla. Rabbim gönlümüzde olanı hakkımızda hayırlı eyle, hakkımızda hayırlı olana gönlümüzü razı eyle",
  "Kuran’ın indirildiği bu kutlu gecede maddi ve manevi tüm sıkıntılarımızdan kurtulmayı nasip eyle… Günahlarımızı affet Ya Rabbim. Hayırlı Kandiller",
  "Ey gecenin sahibi, nasıl ki kudretinle geceyi gündüzle örtüyorsan, bizimde hatalarımızı, günahlarımızı, rahmetinle ört… Kadir Gecemiz mübarek olsun",
  "Kusurlar bizdendir, maĝfiret senden, istikâmet sanadır, Rahmetini esirgeme Ya Rahman… Sabrımızı ve tevekkülümüzü arttır, kalbimizi Nur’un ile nurlandır. Amin",
  "Ben Allah’tan isterim. Verirse yüceliğidir, vermezse imtihanımdır. Kadir gecemiz mübarek olsun",
  "Bin aydan daha hayırlı olan Kadir Gecesinde, kainatın yaratıcısı ve alemlerin Rabbi bağışlayıcı ve acıyıcı yüce Allah tüm dualarınızı kabul etsin.",
  "Bu gece kadir gecesi. Edilen dualar kabul, yapılan tövbeler kabul olurmuş.",
    "Allah’ın aşkıyla yan bu gece, Mevlana gibi dön bu gece, secdeye varıp huzura erince, şu fakiride an bu gece. kandiliniz kutlu olsun.",
  "Tüm İslam aleminin Kadir Gecesi mübarek olsun. İslam’ın kadir ve kıymetini bilenlere selam olsun.",
  "En ışıltılı bakışların gözlerinde, en tatlı sözlerin kulaklarında, tüm mutlulukların avuçlarında ve en sonsuz sevgilerin gönlünce yaşayacağı nice mutlu kandillere",
  "Allah’ım; bizleri rahmetinin o engin lütfuyla bağışla, bize merhamet et. Bize hidayet ver ve sırat-ı müstakimden ayırma. Kadir Gecemiz Mübarek olsun",
  "Allah’ım Sen Benim Rabb’imsin. Bense Senin Kulunum… Sen Benim Sahibimsin. Bense Senin Kölenim. Kadir Gecemiz Mübarek Olsun",
  "Gün vardır, bin yıldan uzun gelir bize, bir yıl vardır bir günden kısa gelir bize. Bire bin yazılan bu gecede dua edelim Rabbimiz’e! Hayırlı kandiller.",
  "Kadir Geceniz mübarek olsun! Allah sana sevdiklerinle beraber mutlu ve huzurlu bir şekilde yaşamayı nasip etsin. Hayırlı Kandiller",
  "Sana yalvaracak, af dileyecek yüzü olmadığı halde, affınla, merhametinle kulunun yüzünü güldüren ALLAH’ım, bizleri de Senin nezdinden gelen bir sevinçle sevindir. Hayırlı Kandiller",
  "Allah’ım… Gecemizi bin aydan hayırlı kıldığın gibi; ömrümüzü de bin ömürden hayırlı kıl. Bizi salihler zümresiyle birlikte haşreyle.  Kadir Gecemiz Mübarek Olsun",
  "Bu mübarek gecenin bereketinden nasiplenmek umuduyla Kadir Geceniz mübarek olsun.",
  "Esenlik ve güvenliğin kâinata yayıldığı, rahmet ve lütufların bolca sunulduğu Kadir Geceniz mübarek olsun.",
  "Rabbim sen içimizden geçenleri en iyi bilensin… Dualarımızı da kabul et. Kadir gecesimiz mübarek olsun.",


];

