class TumTekerlemeler {
  String? Harf;
  String? LottieLink;
  List<String> Tekerlemesi;

  TumTekerlemeler(
      {required this.Harf,
      required this.LottieLink,
      required this.Tekerlemesi});
}

List<TumTekerlemeler> TekerlemeListele = [
  TumTekerlemeler(
      Harf: 'A',
      LottieLink: 'https://assets7.lottiefiles.com/packages/lf20_oxkv3tux.json',
      Tekerlemesi: [
        'A be kuru dayı ne kuru sarı bu darı a be kuru dayı',
        'Abana’dan Adana’ya abarta abarta apar topar ahlatla ağdalı avuntucu ahmak '
            'Ahmet’in avandanlıklarını aparanlardan Acar Abdullah ile Aptal Abdi akşam akşam bize geldi',
        'Adalardan adalara adanan Adanalı Abroşun abarta abarta, '
            'Ahlatlı ağdacının avutucu, avutucu ahmak, aptal Abdurrahman’ın apraşı ağır ağır gidiyordu',
        'Adem madene gitmiş.Adem madende badem yemiş. Madem ki Adem madende badem yemiş, niye bize getirmemiş',
        'Al bu takatukaları takatukacıya takatukalatmaya götür. '
            'Takatukacı takatukaları takatukalamam derse, takatukacıdan takatukaları takatukalamadan al gel',
        'Alem ala dana aldı ala danalandı da biz bir ala dana alıp ala danalanamadık',
        'Aliş’le Memiş mahkemeye gitmiş. Mahkemede mahkemeleşmişler mi mahkemeleşmemişler mi?',
        'Almanya’dan avdet eden Akşehirli Abdullah Alaeddin’in atölyesindeki altı adet aleti aptal Abdi ile ağabeyi mi birlikte aşırıp aldılar da askıya astılar, yoksa'
            ' Alaiye’li adalet Adile’nin oğlu ak suratlı ahmak Ahmet’le Abadanlı Abidin’in'
            ' akrabası arap Asaf mı birlikte aşırıp askıya astılar?',
        'Arabalı Arif aç adalı afacan Ağrı’lı aşçının ailesiyle ajansta akıllı alışkan '
            'amelenin anasına apansız armutçu asalak aşırı atak avare Ayaşlı’yla azizlik etti',
      ]),
  TumTekerlemeler(
      Harf: 'B',
      LottieLink: 'https://assets7.lottiefiles.com/packages/lf20_ywlzta8t.json',
      Tekerlemesi: [
        'Baba Baki Bandırma’lı bacının basmalarını Balıkesir’li bakkal Basri’ye sat',
        'Babaeskili babacan Bahri Beberuhi Bedri ile bıyıksız bıçkıcıbıngıldak Bigalı bekes Bahir’in'
            ' Bigadiç’teki bonbon bonmarşesine varmışlar,oradakilerin yüzlerine bön bön bakarak,'
            'büyülü büyük buhurdanlığı buğulu buğulu boşaltıp bomboş bırakmışlar, sonra da bodrumda gözden kaybolmuşlar',
        'Babasının benekli bıldırcını bitişik bostanda böceklerden bunalarak büzüldü',
        'Bacaksız Basri balıkçı badik balinin balıklarına basa basa bangır bangır bağırttı',
        'Baldıran dalları ballandırmalı mı, ballandırmamalı mı? Sonra o bala daldıran baldıran dalları dallandırmalı mı, ballı dala dallandırmalı mı?',
        'Barakada bıraktığı bardaklara, böceklerin bulaştığını bildiren barbutçu barmen, büyük barın bitişinde büyük bardakla biraya başladı',
        'Batı tepede tahta depo dibinde beytutet eden putlu dede tekkesinden matrut bitli Vedat,'
            ' dar derede tatlı duttan dürülü pide yutup pösteki dide dide dört ayda dört türlü derde tutuldu',
        'Becerikli Bedri bebekli beyzadelere belediyeden bedava bez becerdi',
        'Bıyıklı bıldırcınları bırakmak için bıçak aradı',
        'Bilgili bir bildik bilgisiz bir bildikten binbir kere daha iyidir. Bilmeyenler bilmediklerini bilseler bilirlerdi',
        'Bir berber bir berbere beri gel birader beraber bir berber dükkânı açalım demiş',
        'Bir pirinci birinci buluşta bir inci gibi birbirine bağlayıp perlepe berberi bastı bacak Bedri ile beraber Bursa barına parasız giden paytak budala babası topal Badi’den biberli bir papara yedi',
        'Bir tarlaya kemeken ekmişler. İki kürkü yırtık kel, kör kirpi dadanmış. Biri erkek kürkü yırtık kel, kör kirpi, öteki dişi kürkü yırtık kel, kör kirpi. Kürkü yırtık erkek kel, kör kirpinin yırtık kürkünü, kürkü yırtık dişi kel, kör kirpinin yırtık kürkünü, kürkü yırtık dişi kel, kör kirpinin yırtık kürküne, kürkü yırtık dişi kel kör kirpinin yırtık kürkünü, kürkü yırtık erkek kel, kör kirpinin yırtık kürküne eklemişler',
        'Bizde bize biz derler, sizde bize ne derler?',
        'Bizim damda var beş boz başlı beş boz ördek. Sizin damdaki beş boz başlı beş boz ördek, bizim damdaki beş boz başlı beş ördeğe: siz de bizim gibi beş boz başlı beş ördek misiniz, demiş.',
        'Bol bol yiyen, bel bel bakar.',
        'Bostanda boğazlaşan Bodrum’lu boksör bol bol boyalı boruları boylu boyunca boyadı.',
        'Böceklenen börekleri bölük bölük bölenler böbürlendiler.',
        'Bre berber buraya bak, başı benekli, burma bıyıklı, beti benzi bembeyaz, beberuhi boylu Bilal’in burnuna biber kaçınca bir bebek gibi bar bar bağırması bir bakıma hoş, bir bakıma boş ve berbat bir davranış değil midir?',
        'Bu yoğurdu mayalamalı da mı saklamalı, mayalamamalı da mı saklamalı?',
        'Bu yoğurdu sarmısaklasak da mı saklasak, sarmısaklasak da mı saklasak?',
        'Buruşuk Bulgar bulgur bularak bunak budalayı bunam bunam terletti.',
        'Büyük büstü büklüm büklüm büken Bünyan’lı bücür büyücü bütün bütün büzüldü',
        'Bu tarlaya bir şinik kekere mekere ekmişler. Bu tarlaya da bir şinik kekere mekere ekmişler. Bu tarlaya ekilen bir şinik kekere mekereye boz ala boz başlı pis porsuk dadanmış. Bu tarlaya da ekilen bir şinik kekere mekereye de boz ala boz başlı pis porsuk dadanmış. O tarlaya ekilen bir şinik kekere mekereye dadanan boz ala boz başlı pis porsuk, diğer tarlaya ekilen bir şinik kekere mekereye dadanan boz ala boz başlı pis porsuğa demiş ki; ‘Sen ne zamandan beri bu tarlaya ekilen bir şinik kekere mekereye dadanan boz ala boz başlı pis porsuksun.’ O da ona cevaben sen ne zamandan beri o tarlaya ekilen bir şinik kekere mekereye dadanan boz ala boz başlı pis porsuksan ben de o zamandan beri bu tarlaya ekilen bir şinik kekere mekereye dadanan boz ala boz başlı pis porsuğum demiş.'
      ]),
  TumTekerlemeler(
      Harf: 'C',
      LottieLink: 'https://assets7.lottiefiles.com/packages/lf20_t1yri72f.json',
      Tekerlemesi: [
        'Caddedeki canfesci Canan’ın camındaki canfeslerin cazibeleri cariyelerin canını cayır cayır yaktı.',
        "Camadanlı cahil Cabi Canib’in cacığına cascavlak cadaloz bir canavar gibi saldırdı.",
        "Cambaz Cevat cılız cimri coşkunla cömertliğe cumbada cüret ettiler.",
        "Canı sıkkın cani casusa cazibeleştirilmiş cehaletinden bahsederken, contacı Cumhur, cıvayı cumburdata cumburdata caka satarak yanlarından geçti",
        "Cemil, Cemile, Cemal cumaları cilacı cüce Canip’in cicili bicili cumbalı ciltevinde cümbür cemaat cacıklı civcivle cücüklü cacık yerler, sonra da Cebecili cingöz coğrafyacının cinci ciciannesinin cırcırböceğini dinlerler.",
        'Ceylan cemil cevizlikte cezberelı cemalin cezvesini cebine indirdi.',
        "Cezbereli Cemal Cebeci’de cemaatin cesareti ile celalet gösterdi.",
        "Cıvık cıvacının cılız cırcırları cıyak cıyak cırlarken cızbızlar cızladılar.",
        "Cihangir cihetindeki cibiliyetsiz cimri ciğerci cici cins civcivlerini ciblikçinin cila sepetine koydu.",
        "Coğrafya Coşkun’u coşturdu. Coşkun coştu coşturdu.",
        'Cömertlerin cömertliği cömertleri cömertlendirdi.',
        "Cumbada Cuma cumartesi cura ile curcuna çaldı. Curcuna çaldı curladı.",
        "Cüce çinici Celali Hoca gizlice marpuççular içindeki züccaciyecilere gidip içi Çince yazılı cicili bicili cam çubukları cepceğizine indirmiş.Cüce cümbüşçülerin cümlesi cürümlerine cüret ettiler.",
      ]),
  TumTekerlemeler(
      Harf: 'Ç',
      LottieLink: 'https://assets7.lottiefiles.com/packages/lf20_t1yri72f.json',
      Tekerlemesi: [
        'Çankırılı çarıkçı Çakır, çardakta çalgı çalınırken çapulcularla çan çan etti.',
        "Çapakçurlu çapaçul çarkçıbaşı çaylak Zülküf, Çatalcalı çakmakçı çivit Cahit’e: -Behey çaçabalığı, çepiç, çerçi, çakaloz, çayırhorozu, çöpçatan, çurçur, çirişotu demiş!",
        "Çardaklı çeşmedeki çırak, çiçekleri, çobanın çöreğini ve çuvalları çürüttü.",
        "Çarık çorap dolak, ben sana çarık çorap dolak mı dedim?",
        "Çarşamba çarşısında çatalcıla çatıkkaş Çavdar Çavuş çamaşır çantasını çayın çamuruna düşürdü.",
        "Çatalağzı’nda çatalsız Çatalcalı çatalcının çarpık çurpuk çançiçeğini çalçene Çoruhluya çarptırmasına ne dersin?",
        "Çatalca’da topal çoban çatal yapıp çatal satar, nesi için Çatalca’da topal çoban çatal yapıp çatal satar? Karı için mi Çatalca’da topal çoban çatal yapıp çatal satar?",
        "Çekirge’de çelimsiz çetin, çelik çekiççinin çek çek arabasını çekti.",
        "Çetenin çetin çeribaşısı çeşit çeşit çevresiyle çehresini sildi.",
        "Çımacının çıplak çırağı, Çıkrık’taki çıkınını bir çırpıda çınara çıkardı.",
        "Çilingir çiftlikteki çilli çilekar Çingene çipile çifte attı.",
        "Çilli çekici çılgın çocuk, çökük çardağın çam çerçevelerini çekçek içinde çiviledi.",
        "Çimentodan çirkin çini çipil çiçekçi çilli çilekar çingeneye çifte attı.",
        "Çolak çobanın çorapsız çopur çocuğu, Çornar’dan çoluk çocuğunu çorak yerlere kaçırdı.",
        "Çömelen çömez, çörekleri çöplenirken çöküntü oldu.",
        "Çubukluktaki çukura çuvaldızlı çuvalcıyla çubuk çuhacı düştüler.",
        "Çünkü çürükçü çüş dedi. Çüşçü çünkü çüş dedi.",
      ]),
  TumTekerlemeler(
      Harf: 'D',
      LottieLink:
          'https://assets10.lottiefiles.com/packages/lf20_rv5jhp5v.json',
      Tekerlemesi: [
        "Dadaylı dadımın Dodurgalı düdük delisi dedesi diline doladığı debdebeli dedim dedisiyle dırdırını dilinden düşürüp de bir kez olsun doya doya düden diyemeden, düdenin dallara doldurduğu doyumlu yemişlerden doyasıya yiyemeden dâr-ı dünyadan göçüp gitti.",
        "Dadaylı davulcu davuluna dayanan davut dayıyı darbukayla darb etti.",
        "Damdan geldim, dedem dedim, demli çay istiyor.",
        "Dardünyada delilerle dertli dedeler içinde didindin durdun da kendi derdini döküp dereden tepeden dört çift lakırdı edecek bir hemderdi neden bulamadın?",
        "Davulcu dede dışarlıklı dikişçiyi dolandırırken dönemecin duvarından düştü.",
        "Dedemanda dayımın düdük delisi debdebeli deli dolu Doğan, doya doya doydum demeden, dedim dediye dırdıra düşmeden gitti.",
        "Değirmene girdi köpek, değirmenci çaldı kötek, hem kepek yedi köpek, hem kötek yedi köpek.",
        "Derviş dede destanlarım derlemekten dertlerine devam edemedi.",
        "Dım dım da dım dım, dım dım da dım dım, dım dım da dım dım, ben bu dımdımdan bıktım.",
        "Dır dır dırlanan dışarıda dımdızlak dırlandı.",
        "Didim Didim dit dedim dedeme, dom dom konuşma.",
        "Dilber dilbaz dindar dilavere dilbaz diyerek, dikişlerini dikti.",
        "Doksan dokuz dolaplı doktor dolandırıcı dondurmacıdan dopdolu dondurma dolabı aldı.",
        "Dombaylı dümbül düdük dümbelekçi düdükçünün debdebe delisi dadaylı dedikoducu didaktik dedesi Dodurgalı didikçi dudu dadısı ile dudaksıllaştırmadıkları için durup dinlenmeden dadadididödödududüdüdododıdı dedi durdu.",
        "Dört deryanın deresini dört dergahın derbendine devrederlerse: Dört deryanın deresini dört dergahın derbendine devrederlerse, dört deryadan dört dert, dört dergahtan dört dev çıkar.",
        "Dörtyollu döşemeci döşemelerin döşüntülerini dört köşe döşeklere döndüre döndüre döktü.",
        "Dubaracı Dursun dutluğun duvarındaki durakta durdu.",
        "Dum dum kurşunu düm düm değil, dom dom patlar.",
        "Düdüklü düğmeci Dünden beri düşüne düşüne düğme düzünelerini düzgün düzeltemedi.",
        "Düşkün düşündes düşünselde düşçü düşümsellikle düşünceleme düşselliğini düşünüden düşürmez. Düşürtürse eğer düşüncelik düşüncesizlikle düşündürücü bir düşüncellik kazanır.",
      ]),
  TumTekerlemeler(
      Harf: 'E',
      LottieLink: 'https://assets9.lottiefiles.com/packages/lf20_vk8vizoq.json',
      Tekerlemesi: [
        "Ebe Ece, edepli Efe egemen eğitimde ejderli ehliyetini ekleyerek ellerini emeklinin entrikacı spekürcü erkek esmer eşine etejerli evinde eyvah diyerek ezberletti.",
        "Ecelerin Eveabat’taki evlerindeki tekir kedi, tenceredeki elli dirhemeti kendi kendine yedi.",
        "Eğer, Eleşkirtli eleştirmen Eşref ile Edremitli Bedri’yi Ege’nin en iyi eyercisi biliyorlarsa, ben de en iyi Ermenekli Erdem, Ergene’nin en iyi elektrikçisidir derim.",
        "Elalem bir aladana aldı aladanalandı da biz bir aladana alıp aladanalanamadık.",
        "Ertenekli Örtenekli, Ergene’nin ecesi, Esentepe’nin eğlencesi, erdenler erkete Erdemle bize geldiler.",
        "Erzurumlu Efruz Efendi’nin evde kalmış, evlenememiş ebesi, Edirne emini İskender Efendi’ye, “evet” deyip evlenmelide mi ev edinmeli, yoksa evlenmemelide mi ev edinmeli.",
        "Eylememe, ne naminin nağmeli mani mırıldanma manisine ne de mehmene namına nane mane emmene mani olur demiş.",
        "Ezineli emin Emin’in kızı ellilik Emine, bir eli ile mendilini salladı, bir eli ile elli bine el elleyip zengin oldu.",
      ]),
  TumTekerlemeler(
      Harf: 'F',
      LottieLink: 'https://assets9.lottiefiles.com/packages/lf20_p7ot2wj6.json',
      Tekerlemesi: [
        "Fakat farfara fareler falancanın falanını falsosuz familtesitle fakir fabrikada faydalandılar.",
        "Farfara felfelek fırıl fırıl fileli folluğu fötr fuarında füzelendi.",
        "Farfaracı Fikriye ile favorili faso fiso Fahri, Fatsalı Fatma’yı görünce, fesleğenci feylesoy Feyyaz’ı fındıkçı Ferhunde’yi anımsatarak feveran ettiler.",
        "Fasa fisocu Fikret, Fatsalı ile fesleğenci Feyyaz’ın fındıkçı Ferhunde’si Felemenk’e fink atmaya gittiler.",
        "Felemenkte Felemenklerin Felemenkçe mi konuştuklarını düşüne düşüne fertliği çektiler.",
        "Feraceli Fethiye fener yolunda feminist Feride feryat etmekle fenalaştı.",
        "Fermanlı fabrikatör farmason Fuat, filden, fiilden, fısıltıdan, fosildan, flütten, filitten, fötrden fellik fellik kaçar.",
        "Fındıklı’da fıçıları fırçalayan fıçıcı, fıçıları fırıl fırıl fırlattı.",
        "Fingir firgir fingirdeyen fıkırdak fare, Ferhat’ın fokurdayan kafasına kafesinden ufak ufak fındıkları fırlattı.",
        "Fitneci Fikret firketeli Filiz’le fidanlıktan fiskoslaşarak firar ettiler.",
        "Flütçü Füsun, füzeni füzeyle karaladı.",
        "Fondoncu fondonları fokur fokur fokurdattı. Fokurdattı. Fokurdattı.",
        "Fötr, fötrleri, fötrlere. Fötr, fötrleri, fötrlere mi?",
        "Futbolcular fundalıkta futbol oynadıklar. Oynadılar oynattılar.",
        "Füsun fünvarı füzulen karaladı. Fünvar fuzulen karalandı.",
      ]),
  TumTekerlemeler(
      Harf: 'G',
      LottieLink: 'https://assets9.lottiefiles.com/packages/lf20_oyx0fi12.json',
      Tekerlemesi: [
        "Galata Kulesi kapısı karşısındaki kuru kahvecinin gıgısı çıkık, dişi kırık kurbağa kafalı, karakoncoloz kalfası halkı karışıklığa getirip kahveye kavruk kakula kırığı kattı.",
        "Galatalı gamsız Galip, gammazlıktan suçlanıp gazetecilikten gazlandı.",
        "Galip, Gebze’de gır gır giden gocuklu göçmen gururluya güldü.",
        "Geçen gece Gemerek’ten Gediz’e gelen Gebzeli gezginci gizemcilerden gitarist general Genzel, gençlere gerçekdışılıkla gerçeklik dışı ilişkiler arasında ne gibi bir geçerlilik gerçekliliği olduğunu sordu.",
        "Geçimsiz gelin, Gebze’den, gelinliğindeki gerdanlığı getirdi.",
        "Gıdasızlıktan gıcır gıcır gıcırdayanlara gıdıklanmaktan gına geldi.",
        "Gizi gerçeklerini gırgır gargara gizleyen garip gurultulu gürültülü döngülere gonk gonklamadan güzel günler görme gayretini rüzgara söylemiş.",
        "Gizlice gizlenen, Giritli gibi giyinen Giresunlu girdaba girdi.",
        "Goriller gonklarla golf sahasına girdiler.",
        "Gözleri görmeyen Gölcüklü Gönül, gölgesinden gövdesini gönülsüz gönülsüz gözetti.",
        "Gûlyabaniler, gurbette gurul gurul gururlandılar.",
        "Gül dibi bülbül dili gibi, gül dibi bülbül dili…",
        "Güneyli girgin gammaz Galip Gavurdağı’nda güpegündüz galeyana gelmiş de, Gülgiloğlu Gaziantepli Gazup gazinocuyu Gölköylü gitaristle birlikte Gümüşhane’ye göndermiş.",
        "Güzel günlere güvenen gürbüz Gürcü, gürül gürül gürledi.",
      ]),
  TumTekerlemeler(
      Harf: 'Ğ',
      LottieLink: 'https://assets9.lottiefiles.com/packages/lf20_oyx0fi12.json',
      Tekerlemesi: [
        "Dağı dağı sağlar bağı bağlar bağlar yağı yağlar dağlar soğan soğana ağlar.",
        "Sen ağa ben ağa bu ineği kim sağa?",
        "Ciğerleri çiğ çiğ boğazlayan çığırtkan düğümlenen boğazını öğütçü papağana soğuk yoğurtla ağlaya ağlaya bağlaya bağlaya dağlaya dağlaya açtırdı.",
        "Kuğuları çiğ çiğ boğazlayan Boğaziçili bağcı düğümlenen ağını kazağının boğazına bağlarken yağmur yağıyordu. İğ gibi tığ gibi soğuk yoğurdun buğusu da soğüşlü dağın uğultulu ağıtlarıyla bağdaşıyordu.",
      ]),
  TumTekerlemeler(
      Harf: 'H',
      LottieLink: 'https://assets3.lottiefiles.com/packages/lf20_z1gdtcp8.json',
      Tekerlemesi: [
        "Habeş hemşire, hırkalı hizmetçi hoppa hödüğe hurmaları hürmetle sundu.",
        "Hahamhanede hahambaşı hahamı homur homur homurdanır görûnce, hemencecik heyecanlandı, hızlandı, hoşnutsuz hırçın halhallarla halkaları, halatları hallaçlara verdi.",
        "Hakime hakem, hakeme hakim gerek.",
        "Halam halhallarla halkaları, halatları hallaçlara verdi.",
        "Havzalı Haydar, hancı Haydar’ın hasretinden, hastanedeki haşhaşçı halka haykırarak havalandırdı.",
        "Heceye hevesli heykeltıraş, heybetli heybesini hemşiresi Hendekli Esma’ya hediye etti.",
        "Hımhım, hırçın Hıristiyan, hırsızlıkla hıyarları hızlı hızlı hıfzetti.",
        "Hiçlik herkesi hastalık hastası halinde hırpalayan, nahoşça hırpalayabilen hain hislerdendir.",
        "Hilebaz Hilmi, Hindistan’dan hizmetçi Hintli Hikmet’i hile ile himayesine getirdi.",
        "Horasanlı hoppa hoca, hokkabaz hoyrat Hozatlı’nın horozuna hoyratlıkla hoşafları döktü.",
        "Hödük, Höyük’te höykürerek hörgücünü höpürdetti.",
        "Hulusi, Huriye’nin huzuruna hükmetti.",
        "Hükümlü Hüseyin, hünerine hürmetsizlikten, hüzünlü hüzünlü Hüsnü’yle hüngür hüngür ağladı.",
      ]),
  TumTekerlemeler(
      Harf: "I",
      LottieLink: "https://assets3.lottiefiles.com/packages/lf20_hi0usqe8.json",
      Tekerlemesi: [
        "Iğdır’ın ığıl ığıl akan ılıman ırmağının kıyıları ıklım tıklım ılgın kaplıdır.",
        "Ilım ılınan, ılıcalı ılıcalı akan ılık Iğdır Irmağı’nın kıyıları ıkır tıkır ığrıp ağaçlarıyla kaplıdır.",
        "Issız Sivrihisar’ın sarsıntısız şosesi üstünde zırıltısız sızıltısız bir yaz köşesi seçip sazsız, cazsız ve susuz, içkisiz sırf sosisonla işsiz bir yaz sürmek isteyişimizin sırrını sezişinize serzenişsizce sustum.",
      ]),
  TumTekerlemeler(
      Harf: "İ",
      LottieLink: "https://assets3.lottiefiles.com/packages/lf20_hi0usqe8.json",
      Tekerlemesi: [
        "İbibiklerin ibibiklerini iyice iyileştirmek için İstinyeli istifçi İbiş’in istif istiridyeleri mi, yoksa, İskilipli İspinoz işportacı İshak’ın işliğindeki ibrişimler mi daha iyi, bilemiyorum.",
        "İbiş’le Memiş, iş miş dememiş, itişmiş, kavga etmiş, mahkemeye düşmüşler, mahkemeleşmişler. İş miş dememiş, itişmiş, kavga etmişlerde mi mahkemeye düşmüşler; iş miş demiş, itişmemiş, kavga etmemişlerde mi mahkemeye düşmüşler?",
        "İbiş’le Memiş, mahkemeye gitmiş, mahkemeleşmiş mi, mahkemeleşmemiş mi?",
        "İnim inim inleyen ibiliklerin, ibibiklerin ibiklerini ibrişimli iplikle ipil ipil istifleyen İskilli İskilipli’nin işliğinde toplandık.",
      ]),
  TumTekerlemeler(
      Harf: 'J',
      LottieLink: 'https://assets3.lottiefiles.com/packages/lf20_5dkoszyc.json',
      Tekerlemesi: [
        "Jale Japonyalı jandarmadan Japonca öğrendi.",
        "Jale’nin jurnâlci Jilet Japon’u jambon, jeton, jarse istedi.",
        "Jarseli jeolôg jestini jeolôjide yaptı.",
        "Jiletçi, jileti jiletçiden aldı.",
        "Jimnastikçi Japon jeolôg, jübiledeki jüriye jürnâl satıp, jiletini jurnaliyle jüriye verdi.",
        "Jurnâlci Jale ile jenaratör Müjgân, Japonya’dan jilet, jant, jet, jambon, jelatin, jartiyer, jeton, jarse, Japongülü getirdiler.",
        "Jülide, jübilesinde jüriyle Jüpiter’e yalvardı.",
      ]),
  TumTekerlemeler(
      Harf: 'K',
      LottieLink: "https://assets3.lottiefiles.com/packages/lf20_uco7tvkc.json",
      Tekerlemesi: [
        "Kafakâğıdını kabadayı Kadir’e kaptıran kapkaççı Kasım’ın Kahire’deki kalecikli kaparozcusu geldi.",
        "Kalın kafalı Kadri kabak kafalı kambur kasapla kayaşta kara kargaları kayadan kaldırdı.",
        "Kara kahküllü ketenli kız, kibar komşusuna, köprülü kuyuda küstü.",
        "Kara kazın kısa kayışını kasışına kızmayışına şaşmışsın da, kuru kazın kazışıp kayışı kazısına şaşmış kalmışsın.",
        "Karaburunlu kabadayı Kadir, kafakâğıdını Kadirlili kadir bilmez kapkaççı Kasım’la, Kahire’deki Kalecikliler kahvehanesinde kalamarla kafuru satan kaparozcu Kuzguncuklu Kozmonot Kâzım’a kaptırmış.",
        "Karabüklü kabadayı, kafakağıdını Kalecikli Kazım’a kaptırdı.",
        "Karakış karlıdağı karla kavururken, kaşı kırkık kırk kulaklı Kasım, kırk kırık küp ve kırkık kırk kuzu ile tokmaklı Kırkız Kalesi kapısında karkasının gerilerini kızgın kargılarla dağladı.",
        "Kasımda, Kâzım’la Kasım dayım, daima, sahi, Salih sen sabah sabah sahneden sahaya Hamit’i sahadan sahneye de Hamide’yi mi yolladın, diye sorar.",
        "Kaynayan kazan kapak tutmaz.",
        "Kâni’nin kafası Kâbil’i kabil değil kabûl etmez.",
        "Kekeme Kerim, kemençeci Kemal’le kerestecilik yaptı.",
        "Kelkitli kekeme kel Kenan kestane kerestecilerindeki kertenkeleleri keskin keserle kesti.",
        "kerevet, kereviz, ketenhelva, kendir, kenevir, kemençe, kelem, kekik, keklik satıp kelepircilik ederek rahatıma baksaydım, diyor.",
        "Keşmekeşli kekeme Kerim, Kendirlili ketenhelvacısına, kemik, kekik, kendir, kenevir sattı.",
        "Kıkır kıkır kıkırdayan küfeci, külüstür Kürşat’a küfür etti.",
        "Kınıklı, kılıbık kırpıntı Kıyasettin, Kırımlı kılkuyruk kıtmiri kıkır kıkır kıkırdatarak küskütük küçümen küfeci külhaniyle külüstür Kürşat’ı külünklü küngür üstüne küttedek devirdi.",
        "Kırgızlı kıkır kıkır kıkırdayan kıkırdakçı, kızıl kırlangıç beslemiş.",
        "Kırıkhan’daki kırıkçı kırçıl Kıvanç’ın kırgın kırıkçısı, kırmızı kırda kıkır kıkır kıkırdayarak Kırımlı kıkırdakçının kızıl kırlangıçlarını besliyormuş.",
        "Kırk kırık küp, kırkının da kulpu kırık kara küp.",
        "Kıyma kıyamayan kırık kollu kasap Keramettin, karşıda körkütük kıyma kıyan kasap Kâmil’den kokmuş kokoreç aldı.",
        "Kıymetli kınacı kıyas kına kırıntılarını kışın kınık kırmızı kılıfa kımıldatmadan koydu.",
        "Kikirik kuşçubaşının kilimci kirlozu kuşbaz Kurut Kuşadası’na kukumav kuşu götürüp kişiliksiz kuskusluya vermiş.",
        "Kilimleri kilere kirli kirli kilitleyen Kilisli kibar kimyacı kibirli kibritçinin kitaplarını kiraladı.",
        "Kilisli Kemalettin, kişiliksizlere kilim satıyor.",
        "Kilisli kikirik kilimci, Kilizman’daki kilitli kilisede kimliğini kimseye sezdirmeden, kucak kucak kuskuslu kuşkonmazı kukumav kuşuna, kişiliksiz ",
        "kulağakaçan kirli kirloz kirpiye de, Kuşadası’nın kuşhanesindeki kuşbaşlı kuşbazla birlikte önce kişnişli kuşüzümünü, sonra da Kumla’nın kumlu kumlu kuşkirazını yutturmuş.",
        "Kimi kere kısık kandil, karanlıkta küçük küpe köpük köpük konan keskin sirkeyi ışıklandırdı.",
        "Koca kokainman, kokorozlana kokorozlana kokoreç yedi.",
        "Koca kokoz kokainman kokorozlana kokorozlana Kazablankalı kozmonot Köstler’e: Kök, kok, köken, kokot, kök sökmek, kokoreç, kökmantar, köknar, köçekçe, körkandil, krematoryum, kösnüklük ne diye sormuş.",
        "Kokorozlanan koca köstek, kostak kostak kostaklanmış, kök sökmek, kösnül kösnül bakmak da ne oluyor, demiş.",
        "Konservatuar konserlerindeki kocaman kontrubasını kolay kolay koyamayan koskos koridorda kornası koltuğunda koşan kornocunun kornosunu kolayca kırdı.",
        "Kökmantarcı Köstler, körkandil ve kösnüklük ne demek diye sormuş.",
        "Kömürcünün köpekleri Köprücü Köyünden kör köftecinin kötü köftelerini yediler.",
        "Kusurlu kunduraları kullanan kunduracı kurnaz Kudret kuşçunun kuşlarının kuyruklarını kusurlu diye kırdı.",
        "Kuşadası’nın kukumav kuşu, kucak kucak kuskusla kumlu kumlu kuşkirazını yutmuş.",
        "Küfürbaz külhanbeyi küçük küfeci Kütahyalı kültürlü küpeciye küstüğünden küstah küfretti.",
        "Kürkçü kürkü kürke küskün küskün kürür, üst üste küskütük koyar.",
        "Kürkü kürke kürkçü ular; kürekçi kürekle kürür karır; kürsü ile kürdan, kürkas, kürit ile küskün, küskütük, kürtün, küriyumla kürevi apayrı.",
      ]),
  TumTekerlemeler(
      Harf: 'L',
      LottieLink: 'https://assets3.lottiefiles.com/packages/lf20_vghwjw9c.json',
      Tekerlemesi: [
        "Lângır lûngur lâflamadan leblebiye lâfebeliği, lüpçülüğü lüplemeden Leylâ’dan Lâle’yi sorun.",
        "Lâtifeci, lâdenci, Lâmia, lâtif lâmbasını lâboratuarda lâkırdıcı halanın lâcivert lâke lâvabosuna halâ koyamadı.",
        "Lâvantacı lekeli Leylâ, leblebici leylek Lemi’ye letafetli leylâkları gösterdi.",
        "Lehistanlı lûngur lânfır likorinoz lâfebesi, lôstromo, Lüleburgazlı Leylâ ile Lâlelili Lâle’ye leblebi ile likör ikram etmiş.",
        "Leyla ile Lalelili Lale´ye leblebi ile likör ikram etmiş. Lüpçüler,lütfen lüzumlu lüzumsuz lakırdıları bırakın da lüzferle rızk, rot, rop, rint, ring, ray, radyoaktivite nedir diye konuşun.",
        "Limoncu Lemi, Lâle’nin lüks lôkantasında lüzumlu malzeme limonluğunda lıngır lıngır lıngırdayan dolu çaydanlığın yanına soluksuz nakletti.",
        "Liseli lirik limonatacı, limancılara limonlu likörler aldı.",
        "Lôsyoncu Lôrt, lôkomotifin lôş lôkantasında lôkumcunun lôkmalarını lôkma lôkma yuttu.",
        "Lügatli Lütfü, lütfen lügatini lütfetti.",
        "Lüleburgazlı lüleci Lüpçü lüfer lüzumlu lüks lüle taşlarını lüp etti.",
        "Lüpçüler, lütfen lüzumlu lüzumsuz lâkırdıları bırakın da lüferlerinizi yiyin, lülelerinizi tüttürün.",
      ]),
  TumTekerlemeler(
      Harf: 'M',
      LottieLink: 'https://assets3.lottiefiles.com/packages/lf20_6yrubv6k.json',
      Tekerlemesi: [
        "Mağaralı Mehmet, mağazada magazinleri makbuzla satmış.",
        "Manken muhtarın, Muşlu Muzaffer’le yaptığı mukavele mutlu sona erdi.",
        "Marmara’daki Karmarişli mermerciler mermerciliği meslek edinmişler, ama Mamak’taki mamacılar manyetizmacılıkla marmelatçılığı meslek edinememişler.",
        "Marmaris’ten Marmara’ya maviş maviş menevişli mermerlerle mermerciler, mamacılar ve marmelâtçılar mırın kırın, mışıl mışıl gittiler.",
        "Maskeli madenci Mardinli mahcup Macit’i malüm manifatura malları ile mahkemede mahküm etti.",
        "Mehmet’in mercan tesbihini imamelemeli mi, imamelememeli mi?",
        "Mehtapta melekleri mest eden meczup Mecdi mezarlıktaki mezarcıları Mevlevi’nin mevlidinde methetti.",
        "Mısırlı mızıkacı mırıl mırıl mırıldanarak mızrağını mızrakla mıymıntıya mıhlattı.",
        "Midesiz miskin minik misafir Miço’nun mikroplu mini mini mika minkalesini yaladı.",
        "Mimik merakını, marifetli Müjgan’a mır mır mırıldanan Mediha, mosmor morarıp monolog söyledi.",
        "Moskovalı model, mosmor morararak modern mozaiklerde mola verdi.",
        "Möbleci mösyö, möbleleri möbleciye satmış.",
        "Muhallebici melankolik Mısırlı Mirza modern mösyöyle Muradiye’de müzik dinledi.",
        "Müessese müdürü Müştak, mühim mücadelelerle kübadil Mükerrem’i mükemmel müdafa etti.",
      ]),
  TumTekerlemeler(
      Harf: 'N',
      LottieLink: 'https://assets3.lottiefiles.com/packages/lf20_jeo5oopc.json',
      Tekerlemesi: [
        "Nakkaş nekre nışadırcı Niyazi noktadaki nöbetçiyle nutukta nükte yaptı.",
        "Namlı Nallıhanlı Nesrin’in nalınlarını nazikâne nergis satan nöbetşekeri alan Nezaket’e vermesine ne dersin?",
        "Nankör nalbant nalları nallamalı mı, nallamamalı mı?",
        "Nargileli Nuri, nameci Nilüfer’e nargilesinden ne nameler dinletmiş.",
        "Nazik nadide, narinlikten namelerini Nallıhan’lı nakliyatçı Nazif’e nankör Naci’yle nakletti.",
        "Nezaketli Nedim nevrastenik neşesiz Necmiye’nin nefesini nezleli neşretti.",
        "Niğdeli Nihat’la nişanlı Nigar nispetsiz Nilüfer’le nihayetsiz nikah ninnisi söyledi.",
        "Nişantası rusfen nişadırlandı.",
        "Niyazi’nin Nüvit’le nöbetleşe normal naklettiği narenciye naklini nöron Nuri’yle numaracı Numan kapmışlar.",
        "Nobran Nadir’in Nallıhan’da naneruhu, nalın, narenciye, nergis alıp sattığı, namlı Nesrin’e de nazikâne nazım, nesir, nesep, nesiç, nemelâzımcılık, nezaket, nikelâj, nüans, nümayiş, nukut, noel, nöbet şekeri üzerine nutuk attığı söyleniyor.",
        "Nobran noter, noktadaki nohutları normalden noksan buldu.",
        "Nöbetçi Nedim, nalbant Nail’i narkozla nakletti.",
        "Nöbetçi nöbetinde nöbetini bekledi.",
        "Nuhkuyulu Nuri’nin nutku numaracıyı nurlandırdı.",
        "Nüfuslu nükteden nümayişçinin numunelik nükteleri nüksetti.",
      ]),
  TumTekerlemeler(
      Harf: 'O',
      LottieLink: 'https://assets3.lottiefiles.com/packages/lf20_xyxns9l6.json',
      Tekerlemesi: [
        "Ocak kıvılcımlandırıcılarından mısın, kapı gıcırdatıcılarından mısın? Ne ocak kıvılcımlandırıcılarındanım, ne kapı gıcırdatıcılarındanım.",
        "Okmeydanı’ndan Oğuzeli’ne otostop yap; Oltu’da volta at, olta al; Orhagazi’de Orhanelili Orhan’a otostopçuluk öğret, sonra da Osmancıklı Osman’a otoydu, fotoydu lotoydu, say dök.",
        "Olmaz olmaz deme, olmayacak dediğin oluyor.",
        "Oluklu’dan Kozlu’ya, Kozlu’dan Oğuzeli’nin Otçuk otogarına oba oba, ot toplaya toplaya Posoflu Osman’ın ocağına vardı.",
        "Oruçlu oduncu oluklu okunu oflaya oflaya orduya doğrulttu.",
        "",
        "",
        "",
        "",
        "",
      ]),
  TumTekerlemeler(
      Harf: 'Ö',
      LottieLink: 'https://assets3.lottiefiles.com/packages/lf20_xyxns9l6.json',
      Tekerlemesi: [
        "Ödemişli ödlek Ömer, öksürüklü Özdemir’in öküzüyle ördeğini öldürmüş.",
        "Öğretmen öğleyin öğrencilere dört öğeden oluşan öğütleri söylemiş.",
        "Öğretmen, özerk öğretimde, örnek çalışmalara destek oldu.",
        "Öküz ölür gönü kalır, yiğit ölür ünü kalır.",
        "Önce öfkeyle öttüğünden Ökkeş’i görmedi.",
        "Özbeöz’ün özbeöz Ödemişli öngörülü öğretmeni Özgüraslan ile Özgülaslan özellikle özerk ön öğretimde öylesine özverili övünç verici ve övgüye değer kişiler ki, hani tüm öğretim örgütleri içinde en özgün örnek onlardır, diyebilirim.",
        "Özellikle özerklik üzerine Özdemir’e özgü, özgün ve özgül özellikleri izleyen Özbekli Özkan’la, Özakman, Izgan, Uzken, Özülken, Ozanlara uzanarak ezeli üzüntülerini azalttılar, azalttılar; sonra da kuşları azat ederek yan gelip yattılar.",
        "Özüne özgü özverili Özgür’ün özellikli özerk öğretimde ödenekli örnek çalışmalarına Ozan Özakman da ortak oldu.",
      ]),
  TumTekerlemeler(
      Harf: 'P',
      LottieLink: 'https://assets3.lottiefiles.com/packages/lf20_vcdducm4.json',
      Tekerlemesi: [
        "Paçavracı paskal patronun paspasını paytak palavracı Pakize’nin paspal papucunu patlattı.",
        "Palavracı peltek pısırık pişkin poturlu pörsük pulcu patladı.",
        "Peltek pehlivan peçeli perişan Perizat’ın pervazı perdesiz peykede pestenkerani pembe pedagogla pençelendi.",
        "Pervasız palavracı, parasız pimponun pötikare paltosuna pompayı püskürttü.",
        "Pınarbaşı’nın pimpirik pompacısı Pötürgeli pazvantoğlu pusatçı, paskalyadan palaskasız pisbıyık paskal Pasin, pülümürlülere pülverizatörün Türkçesini satmış. Pülverizatörün Türkçesi mi ne Püskürteç.",
        "Pingpong, pingpong, pingpong! Piyano pingpong! Piyano pingpong! Piyano pingpong! Piyano pingpong! Ping!… Pong!… Pong!… diyerek Posof’un pisipisi otundan yapılma pisovsu piposunu tüttüre tüttüre petalinise doğru paytak paytak yürüyüp gitti.",
        "Pinti pideci pişkin pideleri pijamalı pisboğaz piyadelere piliçli pilavla pişirdi.",
        "Pireli peynirle perhizli pireler tepelerse, pireli peynirle de pır pır pervaz ederler.",
        "Pohpohçu pinti profesör pofur pofur pofurdayarak hınçla tunç çanak punç içip pülverizatör prospektüsünü papazbalığa biblosunun berisindeki papatya buketinin bu yanına bıraktı.",
        "Polatlılı poturlu pokerci polis pokerde Portekizli posbıyık politikacıyı pohpohlayarak portföyünü boşalttı.",
        "Pösteki pörsük pörsük pörsüdü.",
        "Pötürgeli pompacı pimpirik Pusat’ın posbıyık mı pisbıyık mı oğlu Pulumurlu Pınar’la Pasin’e gitmiş.",
        "Pulcu pulları puflayarak pusulu pusulanın putuna pulladı.",
        "Pürüzsüz püsküllü pülverizatörü püskürte püskürte püfleyerek püreyi yedi.",
      ]),
  TumTekerlemeler(
      Harf: 'R',
      LottieLink: 'https://assets7.lottiefiles.com/packages/lf20_pdnhhg4q.json',
      Tekerlemesi: [
        "Radyolu ressam Rıfkı, rint romancıyla röportajcı robottan rüşvet aldı.",
        "Ramazanda razakızade rastıklı Rasim, raftaki radyonun rabıtasını kesti.",
        "Ramazanda Rizeli Remzi rüküş Rümeyşa’ya rastlamış da: römorkör, riziko, rokoko, Ruhülkudüs, rüzgârgülü, rıhzır, rehabilitasyon, rızk, rot, rop, rint, ring, ray ve radyoaktivite nedir diye sormuş.",
        "Resimli romanlarda dikkatle roman ruhları gören Raziye, arabesk mikrobundan rahatsızlık kaparak verem oldu.",
        "Reşit’le Reşat reklamda rekabeti, refakatten rezalet mertebemize çıkardılar.",
        "Rıfkı’yla Rıza rıhtımda rızklarını aradılar.",
        "Riyaziyeci Rıfat ricaen riyasetini rica etti.",
        "Romanyalı romantik romancı Roza, Roma’da romantik rôl oynadı.",
        "Rönesans römorkörü battı.",
        "Rüşvetçiler, rütbe rütbe rüşvet aldılar.",
        "Rüzgârcı Ruşen, rüzgârda duruldu.",
      ]),
  TumTekerlemeler(
      Harf: 'S',
      LottieLink: 'https://assets2.lottiefiles.com/packages/lf20_pxk20owi.json',
      Tekerlemesi: [
        "Safranbolulu Safinazla Salihlili Salih Sivrihisar’da soğuk almışlar, sinüzit olmuşlar, sonra sımsıkı sarınarak söylenmesiz Seyitgazi’ye varıp, sarımsaklı suteresini susarımsağı ile karıştırarak suyunu süzmüşler.",
        "Salepçi saf Sadık, sahtekâr sabuncu Salih’e salyalar saçarak sağlam saplı sopayla saldırdı.",
        "Sandıklı’da sepetleri sıralı simitçi sofrada sökülen sucukları süpürdü.",
        "Sason’un susuz sazlıklarında sadece soğanla sarımsak yetişebileceğini söyleyen Samsunlu sebzecilerin sözüne sizler de sessizce ve sezgilerinize sığınarak inanabilirsiniz.",
        "Sazende Şazi ile Zifos Zihni zaman zaman sizin sokağın sağ köşesinde sinsi sinsi fiskoslaşarak sizi zibidi Suzi’ye sonsuz ve sorumsuz bir hayasızlıkla ikide bir şikayet ederler.",
        "Sazsız sözsüz, sarsıntısız bir yaz meşesi için işsiz, sessiz, serseri bir Sivrihisarlı isteyişimizin sızısını size serzenişlerle anlatamam ki.",
        "Sedat Tınaz’ın tasası suratsız teyzesine rastlama sezen sıska sülük tazısını tuz tortusu tütsüsüne tutmasıydı.",
        "Selimiye’de sekiz bin sekiz yüz seksen sekiz semerli semerci seçkin semerlerini sedefçi Sefer’e senetsiz sepetsiz verdi.",
        "Sen seni bil, sen seni, bil sen seni sen, seni bil, sen seni, bilmezsen sen seni, patlatırlar enseni.",
        "Sinsi Selim’in senelerdir sarsıldığını söyleyen sümsük Sabiha, sahnede de sonuna kadar susmayacağını söyledi.",
        "Siyah sineklerle sivri sinekler sihirli sinemada sivilceli sivil sipahileri sinirlendirdiler.",
        "Sizin damda var beş boz başlı beş boz ördek, bizim damda var beş boz başlı beş boz ördek. Sizin damdaki beş boz başlı beş boz ördek, bizim damdaki beş boz başlı beş boz ördeğe: siz de bizcileyin beş boz başlı beş boz ördek misiniz demiş",
        "Sokaklarda soluyan solucan soytarı somurtkan sopalı sobacıya sonsuz sorularını sordu.",
        "Sözlükten sözlerini söyleyen Söğütlü Sökmen, söylevindeki sözleri sönük sönük söyledi.",
        "Sungurlulu suçsuz subay suçlu Suriyeliyi su başında susuzluktan susturdu.",
        "Süslü sütçü süzgeçten süzülmüş sütünü, sürtük sünepe süt nineye süzme sütlaç yaptırdı.",
      ]),
  TumTekerlemeler(
      Harf: 'Ş',
      LottieLink: 'https://assets2.lottiefiles.com/packages/lf20_pxk20owi.json',
      Tekerlemesi: [
        "Şaklaban şamdancı Şaban, şatafatlı şatosunda şaşmaz şakrak şairleri şanlı şakrak şapkacısının şarabıyla şaşırttı.",
        "Şamlı, şemsiyeli, şıracı, şişko, şoför Şakir, şölende, şurupçuları şüphelendirdi.",
        "Şavşatlı Şaban, Şarkışlalı şipşakçı Şekip, Şişhaneş´den şeytankuşunu, şiş şiyeyi şişlemiş, şiye keşişe şiş demiş.",
        "Şemsiyeli Şerbetçi Şefik, şehirli şekercinin şebboylarını şezlongunun şeritlerine astı.",
        "Şıkırtıcı şımarık şıkır şıkır oynadı.",
        "Şişeci şirin şişko Şinasi, şirkette şişmanlığından şikayet etti.",
        "Şom ağızlı şoför şosede şoförlük yapıyor.",
        "Şöhretli şövalye şölende şövalyesini şöminede yaktı.",
        "Şöhretsiz Şefik, şimdi, şekilsiz şık şaşkın şapşal şurupçuyu ve şosenin yokuşundaki şişko şıracıyı şıra şölenine çağıracak.",
        "Şu dağda beş boş eşek, beşi de bez yüklü besili beş boz eşek.",
        "Şu karşıda bir dal, dalda bir kartal; dal sarkar, kartal kalkar; kartal kalkar, dal sarkar. Dal kalkar, kartal sarkar, kantar tartar. Şu karşıdaki kara kuru kavak, karardın mı ey kara kuru kavak, sarardın mı ey kara kuru kavak!",
        "Şu karşıda kara kuru kavak, karardın mı ey kara kuru kavak, sarardın mı ey kara kuru kavak!",
        "Şu köşe yaz köşesi, şu köşe kış köşesi, Ortadaki soğuk su şişesi.",
        "Şu şosenin, serili serseri resimleri şasisinin şoşonsuz taşımasına şaşarsınız da, şosenin sansarlaşmış suratlı dişsiz şaşı anası onun şu son şansına şaşmaz mı sanırsınız?",
        "Şurupçu Şule’nin şubesi şubatta şurupları şubelendirdi.",
        "Şüpheli Şükrü, şürekâsını şüphelendirdi.",
      ]),
  TumTekerlemeler(
      Harf: 'T',
      LottieLink: "https://assets2.lottiefiles.com/packages/lf20_6twibhcy.json",
      Tekerlemesi: [
        "Taçlı taze tahtında tahtadan tavandaki tahtaları takır takır takırdatan Talip’i taklit etti.",
        "Tahrilli ve talihli tentürdiyotçu tetik Tahir’le tahterevallici tekinsiz Tevfik’in talimhanede ters türs konuşarak terter tepinip tir tir titremeleri Turhallı tombul Turgut’u tıpış tıpış tosbağa sokaktaki tömbekçiye doğru yürüttü.",
        "Talihli Tahir’in titrek Tevfik’i ters türs söz ederek tir tir titretmesi tahin ve tahıl işini Turhallı tombul, tuhaf Turhan’a vernesi doğru mu?",
        "Taşlı tarladaki terasta talaşlar tutuşunca başlayan telaş, talaşların tamamıyla ve büsbütün tutuşmasıyla artmış. Tututşan talaşları görüp tellaklar telaş ettikçe talaşlar tutuşmuş, talaşlar tutuştukça tellaklar telaş etmiş ve terasın trabzanına tutunmuş bakan Trabzonlu Teşrifatçı titiz Tahsin Tevfik, talaşlar tutuştukça telaş eden tellaklara boşuna telaş ediyorsunuz, demiş.",
        "Tatar tepsici tıknaz titiz tosun, töbekeci tulumbacıyla tütün tüttürdü.",
        "Tembel tefeci teyze terliklerini teker teker terli Tekin’in tepesinden temiz Tekir’e fırlattı.",
        "Tıraşlı tırtıl tıpacı tıknaz, tırnaklarını tıkır tıkır tıkırdattı.",
        "Tilki Tınaz, tekir tavşanı, taşlı topraklı tünelin turuncu tuğlalarla tıkanmış ucundan tuttu.",
        "Titiz, temiz, tendürüst dadım; tadını tattığı tere demetini dide dide dağıttı da hiddetinden hem dut dalında takılı duran dırıltı düdüğünü öttürdü, hem de didine didine dedim dedi, dedim dedi dedi durdu.",
        "Titrek Tevfik, talihli Tahir’i tir tir titretti.",
        "Tokatlı tombalacı tombala torbasını toplarken tombalak torununu tokacı torbasına koydu.",
        "Tokmakçı tokmağını tokmaklattırıyor mu, tokmaklattırmayıp topuzcudan topuz yiyor mu?",
        "Topal Talip’le Tophane’li Tahsin, tahteravalli tahtasından tepetaklak tortop taşların ortasına düştüler de, ne tahteravalli tahtasını tazmin ettiler, ne de tahteravalli tahtasını tamir ettiler.",
        "Tövbekar tömbekeci, tövbe töreninde tömbekiye tövbe ederek tökezledi.",
        "Tövbekâr virtüöz, virtüözlere virtüözlük öğretti.",
        "Tuzsuz tulumbacı Turgut, turnaları tutarak tunç tulumbasına tutkalladı.",
        "Tümenin tüfekçisi, tüneldeki tütüncüyle tütün tüttürdü.",
      ]),
  TumTekerlemeler(
      Harf: 'U',
      LottieLink: 'https://assets2.lottiefiles.com/packages/lf20_porfmzt7.json',
      Tekerlemesi: [
        "Ulubatlı utangaç Ulaş’a uğursuz Ulunay’ın uzun uzun uzattığı urganı uğraşa uğraşa aldı.",
        "Uluborlulu Ufuk, utangaç Ulaş’la uğraşmaktan usandı.",
        "Uluborlulu utangaç Ulviye ile Urlalı uğursuz Ulvi uğraşa uğraşa Urfa’daki urgancılara uzun uzun ulam ulam urgan sattılar.",
        "Umdum umdum, geri yumdum.",
        "Umumunuzun mumu umumumuzun mumudur.",
        "Uyku uyku getirir, uyku et bitirir.",
        "Uzun burunlu umutsuz kulun mumunu mumsuz kutudan ateşlediler.",
      ]),
  TumTekerlemeler(
      Harf: 'Ü',
      LottieLink: 'https://assets2.lottiefiles.com/packages/lf20_porfmzt7.json',
      Tekerlemesi: [
        "Üç tunç tas has kayısı hoşafı.",
        "Ülker, üzüntüsünden, üzüm üzüm üzüldü.",
        "Ürdünlü ünlü üfürükçü Üryani, Ünye, Ürgüp üzerinden ülküdeşlerine, üstüpü, üstübez, üvez, üzüm, üzengitaşı ve üzünç götürürken, Üveyik’ten ürüyerek, üvendirlerini sürüyerek yürüyen üçkağıtçıların ürküntü üreten ünü batasıca ünlemleriyle ürküverdi.",
        "Ürgüplü Hüseyin, üzüm üzüm üzülen, süzüm süzüm süzülen üzümcüye üzüldü.",
        "Üstü Üç taşlı taç saplı üç tunç tası çaldıran mı çabuk çıldırır, yoksa iç içe yüz ton saç kaplı çanı kaldıran mı çabuk çıldırır.",
        "Üveçli Üvezli, Ürgüplü üzümcünün üzüm üzüm üzülen, süzüm süzüm süzülen Ünyeli üzengili güzelini üvendireyle ürüye sürüye götürdü.",
        "Üzüm üzüme baka baka kararır.",
        "Üzüntüden üşüdüğünün ürediğini, ürpererek ünlü ünlemesiyle ünledi.",
      ]),
  TumTekerlemeler(
      Harf: 'V',
      LottieLink: 'https://assets1.lottiefiles.com/packages/lf20_iinytb3v.json',
      Tekerlemesi: [
        "Vanlı valinin valizini vazolarla vantuzları vahşi vatman, vapura koydu.",
        "Varlıklı Veli vırvırcı Vikontla voyvoda vuruşunda vücutlandılar.",
        "Vedat’ı caddede durdurdum da dedim ki: Şu dar dünyada delilerle dertli dedeler içinde didindin durdun da kendi derdini döküp dereden tepeden dört çift lakırdı edecek bir hemderdi neden bulamadın?",
        "Vefasız Vahap, farfara fırıldayışlı vefalı fırıldağını vınlayan yele fırlatan Veli’nin de vaktiyle vefalısıymış.",
        "Venedik’te vebadan vefat eden Vedat’ın veresesi vekâleti velveleye verdi.",
        "Vere vere verem oldu.",
        "Vıdıvıdıcı ve vırvırcı Vanlı Veli’nin Vefalı vatandaşı Vahit vatanseverine veda edip vilayette vola vura vura, vayvaycı Vicdani ve Viranköylü Vahap’la karşılaştı.",
        "Vırvırcı Vedia ile vıdıvıdıcı Veli, velinimeti vatman Vahit’e vilayette veda edip Vefa’ya doğru vaveylasız, velevasız velespitle ",
        "volta vururlarken voleybolcu Vatran, virtüöz Vicdani ve Viranşehirli vatansever, viyolonselist Vecibe ile karşılaştılar.",
        "Vırvırcı vırvır vırladı, vızır vızır vızırdadı.",
        "Vicdansız vikont villasının viraneliğinde vicdansızca vikontesi öldürdü.",
        "Viranede, vıcık vıcık vişne suyunu vurur vurmaz dövünen Vedat, avuçlarını ova ova vücuduna vurdu.",
        "Viranköylü Veli vıdı vıdıcı Vildan’la vır vır etti.",
        "Voleybolda voleybolcu voleybol oynadı.",
        "Vurguncular vurgunda vuruştular.",
        "Vücutlu vükelâ, vüzera vücut ettiler.",
      ]),
  TumTekerlemeler(
      Harf: 'Y',
      LottieLink: 'https://assets1.lottiefiles.com/packages/lf20_4ujflh1q.json',
      Tekerlemesi: [
        "Yakası yağlı Yaşar, yağcının yanındaki yağdan yalnız yaldızlı yaş yazısını çıkardı.",
        "Yalancıoğlu yalıncık Yayla Dağı’nın yahnisini yağsız yiyebilirse de Yayla Dağı’nın yağlı yoğurdundan, Yüksekova’nın yusyumru yumurta yumurtlayan tavuklarından, bir de yörük ayranıyla yufkasından asla vazgeçemez.",
        "Yalvaçlı yelpazeli Yıldız, yirmi yoksul yörükle yumurtalarını yükledi.",
        "Yeni yelpazeli Yekta, yerli yekpare yeleğine yedi yeni yemeni yerleştirdi.",
        "Yıldırım Yılmaz, yıkadığı yılanlarıyla yıldırım yıkıcıları yıldırdı.",
        "Yirmi yiğit yine yiğitlendi.",
        "Yitik yerleri yollarda yorgunluktan, uykusuzluktan yıkıla yıkıla yürüyerek yangın yörelerinden sonra yakalayabildiler.",
        "Yoksul yoğurtçu yol bilir Yozgatlı, yoksulluktan yobaz yolcuya yolunmuş yorganını sattı.",
        "Yöndeş yöresel yönde yörünge yöresi yönergeyle yönetildi.",
        "Yuvarlak Yusuf, yumurtalı yusufçukları yukarı yurttaki yuvalarında yumruklarıyla yumrukladı.",
        "Yüce yürekli yüzbaşı yüzüklüğe yürüyüşte yünlü yüreğe yüz vermedi.",
      ]),
  TumTekerlemeler(
      Harf: 'Z',
      LottieLink: 'https://assets1.lottiefiles.com/packages/lf20_xjbds1vq.json',
      Tekerlemesi: [
        "Zamkçı zevzek zirzop, zilli zorba zurnacıyla züğürtledi.",
        "Zararlı zarif Zahit, zamkçı zavallı zabite zambaklarda zalimlik etti.",
        "Zerzevatçının sepetini sıska sülük, tatsız, tuzsuz, sert sırtlı biri zigzaglar çizen tazı gibi taşıyordu.",
        "Zevzek Zeki, zeminlikteki zehir zerrelerini, Zerrin’in zevci zeybek zenciye zeytinlikte verdi.",
        "Zıpır, zıpzıpçı, zımbacı, zıvanasız zirzopla zırıl zırıl zırlayarak zırvaladılar.",
        "Zihni, zihnini Zeki’nin zikzak çizen zevzek züğürt sözleriyle uzun uzun zorladı.",
        "Ziyankâr Ziya, zibidi Zihni’yle Zincirlikuyu’da Zileli Ziba’nın ziyafetine kondular.",
        "Zonguldaklı zorba zorlukla zorladı.",
        "Zurnacı Zuhâl, zulümden zurnasıyla zuhur etti.",
        "Züğürt züppe, zülüflü Zühre’yle züğürtlendi.",
      ]),
  TumTekerlemeler(
      Harf: '!',
      LottieLink: 'https://assets1.lottiefiles.com/packages/lf20_ewbhfilh.json',
      Tekerlemesi: [
        "Günümüzde akıcı konuşmanın önemi tartışılmaz bir gerçek. Özellikle eğitimciler, sanatçılar, liderler, yöneticiler için düzgün bir diksiyon olmazsa olmazlardan. Bu durum oyunculuk için de geçerli elbette. Hem sahneye çıkan hem de seslendirme yapan oyuncuların, ayrıca seslendirme sanatçılarının akıcı bir şekilde konuşması gerekiyor. Diksiyon tekerlemeleri ve alıştırmaları bu durumda ilk başvurulan kaynaklar oluyor. Diksiyon eğitimleri sırasında ya da bireysel çalışmalarda kullanılan tekerlemeler, mesleki ve kişisel gelişim için yararlı oluyor.\nEğer siz de oyuncu olmak, kamera önünde ya da sahnede yer almak ya da sadece akıcı ve anlaşılır konuşmak istiyorsanız diksiyon alıştırmaları yapabilirsiniz. Sayfamızdaki örneklerden yararlanarak diksiyon çalışmaları yaparak kendinizi geliştirebilirsiniz",
      ])
];
